MedicineHub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings #importing settings 
from django.conf.urls.static import static #importing static after settings so we can map the static and media urls
from shop import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('search/', include('search.urls')),
    path('order/', include('order.urls')),
    path('account/create/', views.signupView, name='signup'),
    path('account/login/', views.signinView, name='signin'),
    path('account/signout', views.signoutView, name='signout'),
    path('', include('shop.urls')),
]

if settings.DEBUG: #mapping static and media url when debug is enabled 
	urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
	path('add/<int:product_id>/', views.add_cart, name='add_cart'),
	path('', views.cart_detail, name='cart_detail'),
	path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
	path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
]

search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
		path('', views.searchResult, name='searchResult'),
]

shop/urls.py
from django.urls import path
from . import views

app_name='shop'

urlpatterns = [
	path('',views.allProdCat, name='allProdCat'),
	path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
	path('<slug:c_slug>/<slug:product_slug>/', views.ProdCatDetail, name='ProdCatDetail'),
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model): #Category of Medicine
	name = models.CharField(max_length=255, unique=True)
	slug = models.SlugField(max_length=255, unique=True) #this is the url path that reciever requests on the browser.
	description = models.TextField(blank=True)
	image = models.ImageField(upload_to='category',blank=True) #upload to category folder when new category is made.

	class Meta:
		ordering = ('name',)
		verbose_name = 'category'
		verbose_name_plural = 'categories'

	def get_url(self):
		return reverse('shop:products_by_category', args=[self.slug])

	def __str__(self):
		return '{}'.format(self.name)


class Product(models.Model): #model for Medicine Products
	name = models.CharField(max_length=255, unique=True)
	slug = models.SlugField(max_length=255, unique=True)
	description = models.TextField(blank=True)
	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	price = models.DecimalField(max_digits=10, decimal_places=2)
	image = models.ImageField(upload_to='product', blank=True)
	stock = models.IntegerField()
	available = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now=True)
	updated = models.DateTimeField(auto_now=True)

	class Meta:
		ordering = ('name',)
		verbose_name = 'product'
		verbose_name_plural = 'products'

	def get_url(self):
		return reverse('shop:ProdCatDetail', args=[self.category.slug, self.slug])

	def __str__(self):
		return '{}'.format(self.name)

shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
	first_name = forms.CharField(max_length = 100, required = True)
	last_name = forms.CharField(max_length = 100, required = True)
	email = forms.EmailField(max_length = 254, help_text = 'eg. ksarthak4ever@gmail.com') #defining some fields attributes for UserCreationForm i.e Optional

	class Meta:
		model = User
		fields = ('first_name', 'last_name', 'email', 'username', 'password1', 'password2') #fields to be shown in the form

shop/views.py
from django.shortcuts import render,get_object_or_404, redirect
from . models import Category,Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage

from django.contrib.auth.models import Group, User
from .forms import SignUpForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout


#Category view

def allProdCat(request, c_slug=None): #Used to show all products in that category
	c_page = None #for categories
	products_list = None
	if c_slug!=None:
		c_page = get_object_or_404(Category,slug=c_slug)
		products_list = Product.objects.filter(category=c_page,available=True) #filtering products according to category 
	else:
		products_list = Product.objects.all().filter(available=True)
	''' Paginator Code '''
	paginator = Paginator(products_list,6) #limiting 6 products per category page
	try:
		page = int(request.GET.get('page','1')) #converting GET request to integer i.e page number 1 so we can store it in page variable
	except:
		page = 1
	try:
		products = paginator.page(page) 
	except (EmptyPage, InvalidPage):
		products = paginator.page(paginator.num_pages)
	return render(request,'shop/category.html',{'category':c_page,'products':products})


#Product View

def ProdCatDetail(request, c_slug, product_slug): #Used to show detail product view
	try:
		product = Product.objects.get(category__slug=c_slug, slug=product_slug)
	except Exception as e:
		raise e
	return render(request, 'shop/product.html', {'product':product})


#Forms View

def signupView(request): #Used to create an account for the User
	if request.method == 'POST':
		form = SignUpForm(request.POST)
		if form.is_valid(): # checking if form details entered are valid or not
			form.save()
			username = form.cleaned_data.get('username')
			signup_user = User.objects.get(username = username)
			customer_group = Group.objects.get(name = 'Customer')  
			customer_group.user_set.add(signup_user)
	else:
		form = SignUpForm()
	return render(request, 'accounts/signup.html', {'form':form})	


def signinView(request): #Used to login user 
	if request.method == 'POST':
		form = AuthenticationForm(data = request.POST) 
		if form.is_valid():
			username = request.POST['username'] #getting username and password from the form
			password = request.POST['password']
			user = authenticate(username = username, password = password)
			if user is not None: #checking if username and password are authenticated 
				login(request, user)
				return redirect('shop:allProdCat')
			else:
				return redirect('signup')
	else:
		form = AuthenticationForm()
	return render(request, 'accounts/signin.html', {'form':form})


def signoutView(request):
	logout(request)
	return redirect('signin')

shop/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="{% block metadescription %}{% endblock %}">
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'css/custom.css' %}"> <!-- because we want custom.css to have priority over css gotten from bootstrap site -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome-all.min.css' %}"> <!-- Adding Font Awesome all.min.css file. Font Awesome is a font and icon toolkit based on CSS and LESS -->
	<title>{% block title %}{% endblock %}</title>
</head>
<body>
	<div class="container">
		<div class="container-fluid bg-light navbar-fixed-top my_top_navbar_div"> <!-- Creating a top navbar for signup and signin -->
			{% include 'top-navbar.html' %}
		</div>
		{% include 'header.html' %}
		{% include 'navbar.html' %}
		{% block content %}
		{% endblock %}
	</div>
		{% include 'footer.html' %}
	<script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
	<script src="{% static 'js/popper.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>
</head>

shop/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
	<p class="text-center">&copy; This E-Commerce site is made by Sarthak Kumar. For any queries contact me on my email id ksarthak4ever@gmail.com</p>
</div>

shop/templates/header.html
{% load staticfiles %}
<header>
	<center>
		<a href="{% url 'shop:allProdCat' %}"><img src="{% static 'img/logo.png' %}" alt="MedicineHub Logo"></a> <!-- Note logo image should be available at the specified static/img/logo.png directory otherwise Perfect Cushion will appear in space of logo -->
	</center>
</header>

shop/templates/navbar.html
<!-- navigation bar taking bootstrap navbar template -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown {% if 'shop' in request.path %}active {% endif %}">  <!-- checking if the shop has categories and products then making its navigation active -->
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Shop
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'shop:allProdCat' %}">All Products</a>
          {% for cat in links %}
          <a class="dropdown-item" href="{{ cat.get_url }}">{{ cat.name }}</a>  <!-- To show products by category --> <!--Making Category of products links available throughout the shop -->
          {% endfor %}
        </div>
      </li>
      {% if item_count > 0 %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-cart"></i>({{item_count}})</a> <!-- using item_count dictionary from the context_processor counter to display no. of items in the cart fot that cart_id -->
      </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'search:searchResult' %}" method="get">
      {% csrf_token %}  <!-- Adding cross-site request forgery token to add a layer of protection in the search form against cross-site request forgery -->
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q"><!-- name="q" as using Q objects for complex lookups and q will be used to display products using search app -->
      <button class="btn btn-secondary my-2 my-sm-0" type="submit"> <i class="fas fa-search"></i> </button> 
    </form>
  </div>
</nav>

shop/templates/top-navbar.html
<div class="container">
	<div class="my_custom_menu">
		<ul>
			{% if request.user.is_authenticated and request.user.first_name %} <!-- checking if user is authenticated and first name of the user is available -->
			<li>
				Welcome, {{ request.user.first_name }} <i class="fas fa-user"></i>
			</li>
			<li>
				<a href="{% url 'signout' %}">Sign Out <i class="fas fa-sign-out-alt"></i></a>
			</li>
			{% else %}
			<li>
				<a href="{% url 'signup' %}">Sign Up <i class="fas fa-user-plus"></i></a>
			</li>
			<li>
				<a href="{% url 'signin' %}">Sign In <i class="fas fa-sign-in-alt"></i></a>
			</li>
			{% endif %}
		</ul>
	</div>
</div>	